### ISSUE TITLE
Usage notes

### ISSUE THREAD

**Issue by chrzyki** [ltgoslo/multitask_negation_for_sa#1]
Thanks for the very insightful publication and for making the code available here! Two minor things/questions:

- I couldn't quite figure out which embeddings were used for training/validating. The model/training both refer to `"../../embeddings/google.txt"` as a default for the embeddings and I used `Google News 2013` from [here](http://vectors.nlpl.eu/repository/) which seems to work fine. Could you maybe clarify what exactly was used? And sorry if this was mentioned somewhere and I just missed it.
- In addition to the dependencies mentioned in the README (`scikit-learn`, `torch`, `torchvision` and `nltk`) I also had to explicitly install (i.e. those weren't pulled as requirements for something else) the following in a fresh environment to get everything up and running: `matplotlib`, `tqdm` and `torchtext`.

Thanks again!

Christoph

**Comment by jerbarnes** [comment]
Hi Christoph,

Thanks for taking an interest in our work! I've made some changes to the readme and pushed them, which should answer your questions. But just to restate 1) the link to the embeddings which wasn't included originally is here https://drive.google.com/open?id=1GpyF2h0j8K5TKT7y7Aj0OyPgpFc8pMNS and 2) yes, you are completely right that these dependencies weren't there. Thanks for pointing both of these issues out!

Let us know how everything goes and if you have any further comments :)

Thanks,
Jeremy

**Comment by chrzyki** [comment]
Hey Jeremy,

awesome, thank you very much for the quick reply & the quick help!

Re-running everything now with the embeddings and it is working flawlessly! Closing this. :)
